apps/jumpserver/urls.py
# ~*~ coding: utf-8 ~*~
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve as static_serve

from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer

from .views import IndexView

schema_view = get_schema_view(title='Users API', renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer])
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^users/', include('users.urls.views_urls', namespace='users')),
    url(r'^assets/', include('assets.urls.views_urls', namespace='assets')),
    url(r'^perms/', include('perms.urls.views_urls', namespace='perms')),
    url(r'^terminal/', include('terminal.urls.views_urls', namespace='terminal')),
    url(r'^ops/', include('ops.urls.view_urls', namespace='ops')),
    url(r'^settings/', include('common.urls.view_urls', namespace='settings')),
    url(r'^common/', include('common.urls.view_urls', namespace='common')),

    # Api url view map
    url(r'^api/users/', include('users.urls.api_urls', namespace='api-users')),
    url(r'^api/assets/', include('assets.urls.api_urls', namespace='api-assets')),
    url(r'^api/perms/', include('perms.urls.api_urls', namespace='api-perms')),
    url(r'^api/terminal/', include('terminal.urls.api_urls', namespace='api-terminal')),
    url(r'^api/ops/', include('ops.urls.api_urls', namespace='api-ops')),
    url(r'^api/common/', include('common.urls.api_urls', namespace='api-common')),

    # External apps url
    url(r'^captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^docs/', schema_view, name="docs"),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
      + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/perms/urls.py
# coding:utf-8

from django.conf.urls import url
from rest_framework import routers
import views
import api

app_name = 'perms'

urlpatterns = [
    url(r'^asset-permission$', views.AssetPermissionListView.as_view(), name='asset-permission-list'),
    url(r'^asset-permission/create$', views.AssetPermissionCreateView.as_view(), name='asset-permission-create'),
    url(r'^asset-permission/(?P<pk>[0-9]+)/update$', views.AssetPermissionUpdateView.as_view(),
        name='asset-permission-update'),
    url(r'^asset-permission/(?P<pk>[0-9]+)$', views.AssetPermissionDetailView.as_view(),
        name='asset-permission-detail'),
    url(r'^asset-permission/(?P<pk>[0-9]+)/delete$', views.AssetPermissionDeleteView.as_view(),
        name='asset-permission-delete'),
    url(r'^asset-permission/(?P<pk>[0-9]+)/user$', views.AssetPermissionUserView.as_view(),
        name='asset-permission-user-list'),
    url(r'^asset-permission/(?P<pk>[0-9]+)/asset$', views.AssetPermissionAssetView.as_view(),
        name='asset-permission-asset-list'),
]

router = routers.DefaultRouter()
router.register('v1/asset-permissions', api.AssetPermissionViewSet, 'asset-permission')

urlpatterns += [
    url(r'^v1/user/my/assets/$', api.MyGrantedAssetsApi.as_view(), name='my-assets'),
    url(r'^v1/user/my/asset-groups/$', api.MyGrantedAssetsGroupsApi.as_view(), name='my-asset-groups'),
    url(r'^v1/user/my/asset-group/(?P<pk>[0-9]+)/assets/$', api.MyAssetGroupAssetsApi.as_view(),
        name='user-my-asset-group-assets'),

    # Select user permission of asset and asset group
    url(r'^v1/user/(?P<pk>[0-9]+)/assets/$', api.UserGrantedAssetsApi.as_view(), name='user-assets'),
    url(r'^v1/user/(?P<pk>[0-9]+)/asset-groups/$', api.UserGrantedAssetGroupsApi.as_view(),
        name='user-asset-groups'),

    # Select user group permission of asset and asset group
    url(r'^v1/user-group/(?P<pk>[0-9]+)/assets/$', api.UserGroupGrantedAssetsApi.as_view(), name='user-group-assets'),
    url(r'^v1/user-group/(?P<pk>[0-9]+)/asset-groups/$', api.UserGroupGrantedAssetGroupsApi.as_view(),
        name='user-group-asset-groups'),


    # Revoke permission api
    url(r'^v1/asset-permissions/user/revoke/', api.RevokeUserAssetPermission.as_view(),
        name='revoke-user-asset-permission'),
    url(r'^v1/asset-permissions/user-group/revoke/', api.RevokeUserGroupAssetPermission.as_view(),
        name='revoke-user-group-asset-permission'),
]

urlpatterns += router.urls

apps/users/urls.py
from django.conf.urls import url
from rest_framework_bulk.routes import BulkRouter
import views
import api

app_name = 'users'

urlpatterns = [
    url(r'^login$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout$', views.UserLogoutView.as_view(), name='logout'),
    url(r'^password/forgot$', views.UserForgotPasswordView.as_view(), name='forgot-password'),
    url(r'^password/forgot/sendmail-success$',
        views.UserForgotPasswordSendmailSuccessView.as_view(), name='forgot-password-sendmail-success'),
    url(r'^password/reset$', views.UserResetPasswordView.as_view(), name='reset-password'),
    url(r'^password/reset/success$', views.UserResetPasswordSuccessView.as_view(),
        name='reset-password-success'),
    # User view
    url(r'^user$', views.UserListView.as_view(), name='user-list'),
    url(r'^user/(?P<pk>[0-9]+)$', views.UserDetailView.as_view(), name='user-detail'),
    url(r'^user/(?P<pk>[0-9]+)/asset-permission$', views.UserAssetPermissionView.as_view(),
        name='user-asset-permission'),
    url(r'^user/(?P<pk>[0-9]+)/asset-permission/create$', views.UserAssetPermissionCreateView.as_view(),
        name='user-asset-permission-create'),
    url(r'^user/(?P<pk>[0-9]+)/assets', views.UserGrantedAssetView.as_view(), name='user-granted-asset'),
    url(r'^user/(?P<pk>[0-9]+)/login-history', views.UserDetailView.as_view(), name='user-login-history'),
    url(r'^first-login/$', views.UserFirstLoginView.as_view(), name='user-first-login'),
    url(r'^import/$', views.BulkImportUserView.as_view(), name='user-import'),
    # url(r'^user/(?P<pk>[0-9]+)/assets-perm$', views.UserDetailView.as_view(), name='user-detail'),
    url(r'^user/create$', views.UserCreateView.as_view(), name='user-create'),
    url(r'^user/(?P<pk>[0-9]+)/update$', views.UserUpdateView.as_view(), name='user-update'),

    # User group view
    url(r'^user-group$', views.UserGroupListView.as_view(), name='user-group-list'),
    url(r'^user-group/(?P<pk>[0-9]+)$', views.UserGroupDetailView.as_view(), name='user-group-detail'),
    url(r'^user-group/create$', views.UserGroupCreateView.as_view(), name='user-group-create'),
    url(r'^user-group/(?P<pk>[0-9]+)/update$', views.UserGroupUpdateView.as_view(), name='user-group-update'),
    url(r'^user-group/(?P<pk>[0-9]+)/asset-permission$', views.UserGroupAssetPermissionView.as_view(),
        name='user-group-asset-permission'),
    url(r'^user-group/(?P<pk>[0-9]+)/asset-permission/create$', views.UserGroupAssetPermissionCreateView.as_view(),
        name='user-group-asset-permission-create'),
    url(r'^user-group/(?P<pk>[0-9]+)/assets', views.UserGroupGrantedAssetView.as_view(),
        name='user-group-granted-asset'),
]


router = BulkRouter()
router.register(r'v1/users', api.UserViewSet, 'user')
router.register(r'v1/user-groups', api.UserGroupViewSet, 'user-group')
# router.register(r'v1/user-groups', api.AssetViewSet, 'api-groups')


urlpatterns += [
    # url(r'^v1/users/$', api.UserListUpdateApi.as_view(), name='user-bulk-update-api'),
    url(r'^v1/users/token/$', api.UserAuthApi.as_view(), name='user-token'),
    url(r'^v1/users/(?P<pk>\d+)/reset-password/$', api.UserResetPasswordApi.as_view(), name='user-reset-password'),
    url(r'^v1/users/(?P<pk>\d+)/reset-pk/$', api.UserResetPKApi.as_view(), name='user-reset-pk'),
    url(r'^v1/users/(?P<pk>\d+)/update-pk/$', api.UserUpdatePKApi.as_view(), name='user-update-pk'),
    # url(r'^v1/user-groups/$', api.GroupListUpdateApi.as_view(), name='user-group-bulk-update-api'),
    # url(r'^v1/user-groups/(?P<pk>\d+)/$', api.GroupDetailApi.as_view(), name='user-group-detail-api'),
    # url(r'^v1/user-groups/(?P<pk>\d+)/user/(?P<uid>\d+)/$',
    #     api.DeleteUserFromGroupApi.as_view(), name='delete-user-from-group-api'),
    url(r'^v1/users/(?P<pk>\d+)/groups/$',
        api.UserUpdateGroupApi.as_view(), name='user-update-group'),
    url(r'^v1/user-groups/(?P<pk>\d+)/users/$',
        api.UserGroupUpdateUserApi.as_view(), name='user-group-update-user'),
]

urlpatterns += router.urls

apps/templates/_base_create_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% block custom_head_css_js %}
    <link href="{% static 'css/plugins/select2/select2.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/plugins/select2/select2.full.min.js' %}"></script>
    {% block custom_head_css_js_create %} {% endblock %}
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>{{ action }}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {% if form.errors.all %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                            {{ form.errors.all }}
                        </div>
                        {% endif %}
                        {% block form %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/_foot_js.html
{% load i18n %}
{% load static %}
<!-- Mainly scripts -->
<script src="{% static "js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static "js/plugins/toastr/toastr.min.js" %}"></script>
<script src="{% static "js/inspinia.js" %}"></script>
<script src="{% static "js/jumpserver.js" %}"></script>
<script>
activeNav();
$(document).ready(function(){
    setAjaxCSRFToken();
    $('textarea').attr('rows', 5);
    if ($('.tooltip')[0]) {
        $('.tooltip').tooltip();
    }
});
</script>

apps/templates/_footer.html
<div class="footer fixed">
    <div class="pull-right">
        Version <strong>0.5.0-{% include '_build.html' %}</strong> GPLv2.
        <img style="display: none" src="http://www.jumpserver.org/img/evaluate_avatar1.jpg">
    </div>
    <div>
        <strong>Copyright</strong> 北京堆栈科技有限公司 &copy; 2014-2017
    </div>
</div>

apps/templates/_head_css_js.html
{% load static %}

<!-- css file -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/vaildator/jquery.validator.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datatables/datatables.min.css' %}" rel="stylesheet">
<!-- scripts -->
<script src="{% static 'js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'js/plugins/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/datatables/datatables.min.js' %}"></script>

apps/templates/_header_bar.html
{% load i18n %}
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <!--<form role="search" class="navbar-form-custom" method="get" action="">-->
                <!--<div class="form-group">-->
                    <!--<input type="text" placeholder="{% trans 'Search' %}..." class="form-control" name="search" id="top-search">-->
                <!--</div>-->
            <!--</form>-->
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message">{% trans 'Welcome to use Jumpserver system' %}</span>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                     <span class="m-r-sm text-muted welcome-message">{% trans 'Help' %}</span>
                </a>
            </li>
            <li class="dropdown">
                {% if request.user.is_authenticated %}
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="m-r-sm text-muted welcome-message">
                        <img alt="image" class="img-circle" width="40" height="40" src="{{ request.user.avatar_url }}"/>
                        <strong class="font-bold"> {{ request.user.name }}
                            <span style="color: #8095a8"></span>
                            <b class="caret"></b>
                        </strong>
                    </span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a href="{% url 'users:user-profile' %}"><i class="fa fa-cogs">  </i><span> {% trans 'Profile' %}</span></a></li>
                    <li class="divider"></li>
                    {% if request.user.is_superuser %}
                        {% if request.COOKIES.IN_ADMIN_PAGE == 'No' %}
                            <li><a id="switch_admin"><i class="fa fa-exchange"></i><span> {% trans 'Admin page' %}</span></a></li>
                        {% else %}
                            <li><a id="switch_user"><i class="fa fa-exchange"></i><span> {% trans 'User page' %}</span></a></li>
                        {% endif %}
                    {% endif %}
                    <li><a href="{% url 'users:logout' %}"><i class="fa fa-sign-out"></i> {% trans 'Logout' %}</a></li>
                </ul>
                {% else %}
                <a href="{% url 'users:login' %}">
                    <i class="fa fa-sign-in"></i>{% trans 'Login' %}
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2></h2>
        <ol class="breadcrumb">
            <li>
                <a href="">{% trans 'Dashboard' %}</a>
            </li>
            <li>
            {% if app %}
                <a>{{ app }}</a>
            {% endif %}
            </li>
            {% if action %}
            <li class="active">
                <strong>{{ action }}</strong>
            </li>
            {% endif %}
        </ol>
    </div>
    <div class="col-sm-2">
    </div>
</div>

apps/templates/_left_side_bar.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            {% include '_user_profile.html' %}
            {% if request.user.is_superuser and request.COOKIES.IN_ADMIN_PAGE != "No" %}
                {% include '_nav.html' %}
            {% else %}
                {% include '_nav_user.html' %}
            {% endif %}
        </ul>
    </div>
</nav>

apps/templates/_list_base.html
{% extends 'base.html' %}
{% load common_tags %}
{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> {{ action }} </h5>
                    <div class="ibox-tools">
                        <a class="collapise-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="">
                        {% block content_left_head %} {% endblock %}
                        <form id="search_form" method="get" action="" class="pull-right mail-search">
                            <div class="input-group">
                                <input type="text" class="form-control input-sm" name="keyword" placeholder="Search" value="{{ keyword }}">
                                <div class="input-group-btn">
                                    <button id='search_btn' type="submit" class="btn btn-sm btn-primary">
                                        搜索
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <table class="table table-striped table-bordered table-hover " id="editable" >
                        <thead>
                            <tr>
                                {% block table_head %} {% endblock %}
                            </tr>
                        </thead>
                        <tbody>
                        {% block table_body %} {% endblock %}
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-sm-4">
                            {# Update batch #}
                            {% block content_bottom_left %} {% endblock %}
                        </div>
                        {% include '_pagination.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/templates/_message.html
{% load i18n %}
{% block first_login_message %}
    {% if request.user.is_authenticated and request.user.is_first_login %}
    <div class="alert alert-danger help-message">
        {% url 'users:user-first-login' as first_login_url %}
        {% blocktrans %}
        Your information was incomplete. Please click <a href="{{ first_login_url }}"> this link </a>to complete your information.
        {% endblocktrans %}
    </div>
    {% endif %}
{% endblock %}
{% block update_public_key_message %}
    {% if request.user.is_authenticated and not request.user.is_public_key_valid %}
    <div class="alert alert-danger help-message">
        {% url 'users:user-pubkey-update' as user_pubkey_update %}
        {% blocktrans %}
        Your ssh public key not set or expired. Please click <a href="{{ user_pubkey_update }}"> this link </a>to update
        {% endblocktrans %}
    </div>
    {% endif %}
{% endblock %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} help-message" >
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

apps/templates/_nav_user.html
{% load i18n %}
<li id="assets">
    <a href="{% url 'assets:user-asset-list' %}">
        <i class="fa fa-files-o"></i><span class="nav-label">{% trans 'My assets' %}</span><span class="label label-info pull-right"></span>
    </a>
</li>
<li id="users">
    <a href="{% url 'users:user-profile' %}">
        <i class="fa fa-user" ></i> <span class="nav-label">{% trans 'Profile' %}</span><span class="label label-info pull-right"></span>
    </a>
</li>
<li >
    <a href="{% url 'terminal:web-terminal' %}" target="_blank"><i class="fa fa-window-maximize"></i>
        <span class="nav-label">{% trans 'Web terminal' %}</span>
    </a>
</li>

apps/templates/_pagination.html
{% load common_tags %}
   {% if is_paginated %}
   <div class="col-sm-4">
       <div class="dataTables_info text-center" id="editable_info" role="status" aria-live="polite">
           显示第 {{ page_obj.start_index }} 至 {{ page_obj.end_index }} 项结果，共 {{ paginator.count }} 项
       </div>
   </div>
   <div class="col-sm-4">
       <div class="dataTables_paginate paging_simple_numbers" id="editable_paginate">
           <ul class="pagination" style="margin-top: 0; float: right">
               {% if page_obj.has_previous %}
                   <li class="paginate_button previous" aria-controls="editable" tabindex="0" id="previous">
                       <a data-page="next" href="?page={{ page_obj.previous_page_number}}">‹</a>
                   </li>
               {% endif %}

               {% for page in paginator.num_pages|pagination_range:page_obj.number %}
                   {% if page == page_obj.number %}
                       <li class="paginate_button active" aria-controls="editable" tabindex="0">
                   {% else %}
                       <li class="paginate_button" aria-controls="editable" tabindex="0">
                   {% endif %}
                           <a class="page" href="?page={{ page }}" title="第{{ page }}页">{{ page }}</a>
                       </li>
               {% endfor %}

               {% if page_obj.has_next %}
                   <li class="paginate_button next" aria-controls="editable" tabindex="0" id="next">
                       <a data-page="next" href="?page={{ page_obj.next_page_number }}">›</a>
                   </li>
               {% endif %}
           </ul>
       </div>
   </div>
   {% endif %}
<script>
    $(document).ready(function () {
        $('.page').click(function () {
            var searchStr = location.search;
            var old_href = $(this).attr('href').replace('?', '');
            var searchArray = searchStr.split('&');

            if (searchStr == '') {
                searchStr = '?page=1'
            }

            if (searchStr.indexOf('page') >= 0) {
                searchArray.pop();
            }

            searchArray.push(old_href);
            if (searchArray.length > 1) {
                $(this).attr('href', searchArray.join('&'));
            }
        })
    });

</script>

apps/templates/_user_profile.html
{% load static %}
{% load i18n %}
<li class="nav-header">
    <div class="dropdown profile-element">
        <div>
            <img alt="image" height="40" src="/static/img/logo.png"/>
        </div>
        <div>
            <a href="http://www.jumpserver.org" target="_blank">Jumpserver</a>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="logo-element">
        <img alt="image" height="40" src="/static/img/logo.png"/>
    </div>
</li>
<script>
$(document).ready(function () {
})
.on('click', '#switch_admin', function () {
    var cookieName = "IN_ADMIN_PAGE";
    setTimeout(function () {
        delCookie(cookieName);
        setCookie(cookieName, "Yes");
        window.location = "/"
    }, 100)
})
.on('click', '#switch_user', function () {
    var cookieName = "IN_ADMIN_PAGE";
    setTimeout(function () {
        delCookie(cookieName);
        setCookie(cookieName, "No");
        window.location = "{% url 'assets:user-asset-list' %}"
    }, 100);
})
</script>

apps/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <title>Jumpserver</title>
    <link rel="shortcut icon" href="{% static 'img/facio.ico' %}" type="image/x-icon">
    {% include '_head_css_js.html' %}
    <link href="{% static 'css/jumpserver.css' %}" rel="stylesheet">
    {% block custom_head_css_js %} {% endblock %}
</head>

<body>
<div id="wrapper">
    {% include '_left_side_bar.html' %}
    <div id="page-wrapper" class="gray-bg">
        {% include '_header_bar.html' %}
        {% include '_message.html' %}
        {% block help_message %} {% endblock %}
        {% block content %}{% endblock %}
        {% include '_footer.html' %}
    </div>
</div>

</body>
{% include '_foot_js.html' %}
{% block custom_foot_js %} {% endblock %}
</html>

apps/templates/delete_confirm.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'Confirm delete' %}</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Are you sure delete' %} <b>{{ object.name }} </b> ?</p>
    <input type="submit" value="Confirm" />
</form>
</body>
</html>

apps/templates/flash_message_standalone.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{{ title }}</title>

    {% include '_head_css_js.html' %}
    <link href="{% static "css/jumpserver.css" %}" rel="stylesheet">
    <script src="{% static "js/jumpserver.js" %}"></script>

</head>

<body class="gray-bg">
    <div class="passwordBox2 animated fadeInDown">
        <div class="row">
            <div class="col-md-12">
                <div class="ibox-content">
                    <div>
                        <img src="{% static 'img/logo.png' %}" style="margin: auto" width="82" height="82">
                        <h2 style="display: inline">Jumpserver</h2>
                    </div>
                    {% if errors %}
                    <p>
                        <div class="alert alert-danger">
                            {{ errors }}
                        </div>
                    </p>
                    {% endif %}

                    {% if messages %}
                        <p>
                        <div class="alert alert-success" id="messages">
                            {{ messages|safe }}
                        </div>
                    </p>
                    {% endif %}
                    <div class="row">
                        <div class="col-lg-3">
                                <a href="{{ redirect_url }}" class="btn btn-primary block full-width m-b">返回</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-6">
                Copyright Jumpserver.org
            </div>
            <div class="col-md-6 text-right">
               <small>2014-2017</small>
            </div>
        </div>
    </div>
</body>
<script>
    var time = '{{ interval }}';
    if (!time){
        time = 5;
    } else {
        time = parseInt(time);
    }
    function redirect_page() {
        if (time >= 0) {
            var messages = '{{ messages|safe }}， <b>' + time +'</b> ...';
            $('#messages').html(messages);
            time--;
            setTimeout(redirect_page, 1000);
        }
        else {
            window.location.href = "{{ redirect_url }}";
        }
    }
    {% if auto_redirect %}
    window.onload = redirect_page;
    {% endif %}
</script>
</html>